name: manage-azure-policy-c8e081bc
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'new/policies/A_maximum_of_3_owners_should_be_designated_for_your_subscription_4f11b553-d42e-4e3a-89be-32ca364cad4c/**'
#      - .github/workflows/manage-azure-policy-c8e081bc.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_c8e081bc}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          new/policies/A_maximum_of_3_owners_should_be_designated_for_your_subscription_4f11b553-d42e-4e3a-89be-32ca364cad4c/**
